DROP SCHEMA PHONES CASCADE;

CREATE SCHEMA PHONES;

USE PHONES;

CREATE TABLE PHONES (
   ID INT AUTO_INCREMENT,
   NAME VARCHAR(20) NOT NULL,
   DESCRIPTION VARCHAR(100),
   IMAGE_PATH VARCHAR(50) NOT NULL,
   PRICE DECIMAL(5, 2),
   CONSTRAINT PK_PHONES PRIMARY KEY (ID)
);

