DROP SCHEMA IF EXISTS CUSTOMERS CASCADE;

CREATE SCHEMA CUSTOMERS;

USE CUSTOMERS;

CREATE TABLE CUSTOMERS (
   ID INT AUTO_INCREMENT,
   NAME VARCHAR(20) NOT NULL,
   SURNAME VARCHAR(100),
   EMAIL VARCHAR(100) NOT NULL,
   CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
);